### ISSUE TITLE
Add support for Meteor

### ISSUE THREAD

**Issue by arunoda** [kadirahq/getstorybook#1]
Detect Meteor projects and add essential configs.

**Comment by arunoda** [comment]
Guys, I need to help to make some default configurations for Meteor.(only on client side) Do you know which babel plugins, webpack stuff we could use?

**Comment by zeroasterisk** [comment]
@arunoda thanks for this!  

I'd also be interested in some simple templates for webpack for `react-cdk` projects, something to get up and running fast with bootstrap3, bootstrap4, material, etc.

**Comment by ffxsam** [comment]
My boilerplate `.babelrc` for Meteor:

``` json
{
  "presets": [
    "es2015",
    "react",
    "stage-1"
  ]
}
```

I use `stage-1` so I can use class properties.. which actually, I heard is in stage-2 now, though that doesn't seem to work for me, so it may not be published to the npm registry yet.

**Comment by arunoda** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;75V8M8qs&#x2F;3-add-meteor-support"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add Meteor support</a>

**Comment by ffxsam** [comment]
On second thought, I also have plugins set:

```
{
  "plugins": ["babel-root-slash-import"]
}
```

**Comment by PolGuixe** [comment]
how to load CSS from Meteor Packages, e.g. Font Awesome?

**Comment by index01d** [comment]
@PolGuixe ugly way, but you can import css directly from ../.meteor/local/build/programs/web.browser/merged-stylesheets.css

**Comment by ilan-schemoul** [comment]
I also taught of using `.meteor/local/build/programs/web.browser/merged-stylesheets.css`  what do @arunoda thinks about that particular way of loading css ?

**Comment by ilan-schemoul** [comment]
Actually it doens't work because my css loads fonts.
My fonts are in /public/fonts, so in my css the url imported is /fonts (as we have to omit /public in Meteor) so when storybook tries to load `merged-stylesheets.css` I have this error (as it doesn't find fonts for above reasons) : 
```
in ./~/css-loader?importLoaders=1!./~/postcss-loader!./.meteor/local/build/programs/web.browser/merged-stylesheets.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./fonts/roboto/Roboto-Thin.woff2 in C:\Easy_16.1.1\eds-www\32-PHARMACIE_METEOR\.meteor\local\build\programs\web.browser
 @ ./~/css-loader?importLoaders=1!./~/postcss-loader!./.meteor/local/build/programs/web.browser/merged-stylesheets.css 6:73027-73070 
```

**Comment by NitroBAY** [comment]
How do you, @index01d, handles this problem.
