### ISSUE TITLE
CRA public directory to Storybook static-dir

### ISSUE THREAD

**Issue by thani-sh** [kadirahq/getstorybook#18]
CRAP supports a `public` directory from v0.5 as described [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#using-the-public-folder). We should add this to the list of static directories by default.

**Comment by arunoda** [comment]
Awesome. 
Send me a PR.

**Comment by arunoda** [comment]
BTW: It's CRA :)

**Comment by thani-sh** [comment]
As I remember, I'm not the one who started using that acronym :P

**Comment by arunoda** [comment]
:)
