### ISSUE TITLE
Show feedback when installing dependencies

### ISSUE THREAD

**Issue by gaearon** [kadirahq/getstorybook#5]
I'm currently stuck on this:

<img width="756" alt="screen shot 2016-08-02 at 17 53 18" src="https://cloud.githubusercontent.com/assets/810438/17337320/05400f0e-58da-11e6-927f-51cce25b6433.png">

I think there should be feedback so the user knows npm isn't just stuck.
Especially given that npm 3 gives you an overall sense of progression.

**Comment by arunoda** [comment]
Yeah! That's a pretty good idea.

**Comment by arunoda** [comment]
Now we show NPM's default output with the `v1.1.0` release. Hope we can close this.
